REST Client用 apiテストツール
###

# プロジェクト取得
GET http://localhost:3002/api/v1/projects/1

###

# セッション取得
GET http://localhost:3002/api/v1/projects/1/sessions/1

###

# セッション更新
PATCH http://localhost:3002/api/v1/projects/1/sessions/1 HTTP/1.1
content-type: application/json

{
 "testerName": "testerName is ore"
}