name: CI

on: [push]

jobs:
  ut:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          yarn install
          yarn typescript-json-validator src/lib/settings/Settings.ts
          yarn typescript-json-validator src/lib/settings/DeviceSettings.ts
          yarn test
