name: Deploy API document to Pages

# on:
#   push:
#     branches: ["main"]

#   workflow_dispatch:

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        run: |
          yarn install

      - name: Generate document
        run: |
          yarn generate:apidoc
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v4.15.5.tar.gz
          tar -xvf v4.15.5.tar.gz swagger-ui-4.15.5/dist
          mkdir -p ./docs/api
          cp swagger-ui-4.15.5/dist/* ./docs/api
          sed -i "s#https://petstore\.swagger\.io/v2/swagger\.json#api\.json#g" ./docs/api/swagger-initializer.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs/api"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
